import { ItemStat } from './types';

export const ARMOR_SLOTS: string[] = ["Zırh", "Kask", "Eldiven", "Ayakkabı"];
export const ACCESSORY_SLOTS: string[] = ["Küpe", "Bilezik", "Yüzük", "Kolye"];
export const WEAPON_SLOTS: string[] = ["Kılıç", "Kalkan", "Çift El Kılıç", "Mızrak", "Çift Balta", "Çift Bıçak", "Yay", "Arbalet", "Asa", "Yaşam Asa", "Savaş Çekici"];
export const BAG_SLOTS: string[] = ["Çanta"];
export const TOOL_SLOTS: string[] = ["Kazma", "Orak", "Bıçak", "Balta", "Olta"];
export const PHYSICAL_WEAPON_SLOTS: string[] = ["Kılıç", "Çift El Kılıç", "Mızrak", "Çift Balta", "Çift Bıçak", "Yay", "Arbalet", "Savaş Çekici"];
export const MAGICAL_WEAPON_SLOTS: string[] = ["Asa", "Yaşam Asa"];
export const ITEM_SLOTS: string[] = [...ARMOR_SLOTS, ...ACCESSORY_SLOTS, ...WEAPON_SLOTS, ...BAG_SLOTS, ...TOOL_SLOTS];
export const ARMOR_TYPES: string[] = ["[Ağır]", "[Hafif]", "[Cübbe]"];
export const STAR_LEVELS: number[] = Array.from({ length: 16 }, (_, i) => i); // 0-15
export const ARMOR_ITEM_LEVELS: number[] = [1, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 60, 75, 100, 110];
export const ACCESSORY_ITEM_LEVELS: number[] = [10, 20, 30, 40, 50, 60, 75, 100, 110];
export const TOOL_LEVELS: number[] = [1, 25, 50];

export const TOOL_GRADE_RANGES: Record<number, { min: number; max: number }> = {
  1: { min: 38, max: 60 },
  25: { min: 64, max: 100 },
  50: { min: 90, max: 140 },
};

export const STAT_OPTIONS: ItemStat[] = Object.values(ItemStat);

export const NO_SET = "Set Yok";

export const STATIC_ITEM_ATTRIBUTES = {
    gender: "Herkese Açık",
    repairCost: "4 / 4,200",
    sellPrice: "0",
    weight: "1.25 kg",
};

export const ARMOR_WEIGHTS: Record<string, number> = {
  "[Ağır]": 10,
  "[Hafif]": 7,
  "[Cübbe]": 4,
};

export const HEAVY_ARMOR_NAMES_BY_LEVEL: Record<string, string[]> = {
  "Zırh": [
    "Buz Bağlı Zırh",
    "Fırtınaya Dövülmüş Zırh",
    "Kalkan Zırhı",
    "Gökler Zırhı",
    "Darp Edilmiş Muhafız Zırhı",
    "Kara Çelik Zırh",
    "Ejderha Derisi Zırhı",
    "Tapınakçı Zırhı",
    "Dreadnought Zırhı",
    "Gürültülü Zırh",
    "Çelik Zırh",
  ],
  "Kask": [
    "Buz Bağlı Kask",
    "Fırtınaya Dövülmüş Kask",
    "Kalkan Kaskı",
    "Gökler Kaskı",
    "Darp Edilmiş Muhafız Kaskı",
    "Kara Çelik Kask",
    "Ejderha Derisi Kaskı",
    "Tapınakçı Kaskı",
    "Dreadnought Kaskı",
    "Gürültülü Kask",
    "Çelik Kask",
  ],
  "Eldiven": [
    "Buz Bağlı Eldiven",
    "Fırtınaya Dövülmüş Eldiven",
    "Kalkan Eldiveni",
    "Gökler Eldiveni",
    "Darp Edilmiş Muhafız Eldiveni",
    "Kara Çelik Eldiven",
    "Ejderha Derisi Eldiven",
    "Tapınakçı Eldiven",
    "Dreadnought Eldiven",
    "Gürültülü Eldiven",
    "Çelik Eldiven",
  ],
  "Ayakkabı": [
    "Buz Bağlı Bot",
    "Fırtınaya Dövülmüş Bot",
    "Kalkan Botu",
    "Gökler Botu",
    "Darp Edilmiş Muhafız Botu",
    "Kara Çelik Bot",
    "Ejderha Derisi Botu",
    "Tapınakçı Botu",
    "Dreadnought Botu",
    "Gürültülü Bot",
    "Çelik Bot",
  ],
};

export const LIGHT_ARMOR_NAMES_BY_LEVEL: Record<string, string[]> = {
  "Zırh": [
    "Orman Zırhı",
    "Alaca Zırh",
    "Sönük Kaşif Zırhı",
    "Kale Koruyucusu Zırhı",
    "Lord'un Vasal Zırhı",
    "Hafif Zırh",
    "Gümüş Zırh",
    "Çaylak Muhafız Zırhı",
    "Şahin Zırhı",
    "Gölge Zırhı",
    "Çöl Avcısı Zırhı",
  ],
  "Kask": [
    "Orman Kaskı",
    "Alaca Kaskı",
    "Sönük Kaşif Kaskı",
    "Kale Koruyucusu Kaskı",
    "Lord'un Vasal Kaskı",
    "Hafif Kask",
    "Gümüş Kask",
    "Çaylak Muhafız Kaskı",
    "Şahin Kaskı",
    "Gölge Kaskı",
    "Çöl Avcısı Kaskı",
  ],
  "Eldiven": [
    "Orman Eldiveni",
    "Alaca Eldiveni",
    "Sönük Kaşif Eldiveni",
    "Kale Koruyucusu Eldiveni",
    "Lord'un Vasal Eldiveni",
    "Hafif Eldiven",
    "Gümüş Eldiven",
    "Çaylak Muhafız Eldiveni",
    "Şahin Eldiveni",
    "Gölge Eldiveni",
    "Çöl Avcısı Eldiveni",
  ],
  "Ayakkabı": [
    "Orman Botu",
    "Alaca Botu",
    "Sönük Kaşif Botu",
    "Kale Koruyucusu Botu",
    "Lord'un Vasal Botu",
    "Hafif Bot",
    "Gümüş Bot",
    "Çaylak Muhafız Botu",
    "Şahin Botu",
    "Gölge Botu",
    "Çöl Avcısı Botu",
  ],
};

export const ROBE_ARMOR_NAMES_BY_LEVEL: Record<string, string[]> = {
  "Zırh": [
    "Pamuk Gezgin Zırhı",
    "Kır Gezgini Zırhı",
    "Doğa Gezgini Zırhı",
    "İnce İpek Kumaş Zırhı",
    "Karanlık Ölüm Gözetleme Zırhı",
    "Yörük Koruyucu Zırhı",
    "Gizli Gezgin Zırhı",
    "Kraliyet Rehber Zırhı",
    "Fidelis Zırhı",
    "Yükselen Soylu Ruh Zırhı",
    "Usta Büyücü Zırhı",
  ],
  "Kask": [
    "Pamuk Gezgin Kaskı",
    "Kır Gezgini Kaskı",
    "Doğa Gezgini Kaskı",
    "İnce İpek Kumaş Kaskı",
    "Karanlık Ölüm Gözetleme Kaskı",
    "Yörük Koruyucu Kaskı",
    "Gizli Gezgin Kaskı",
    "Kraliyet Rehber Kaskı",
    "Fidelis Kaskı",
    "Yükselen Soylu Ruh Kaskı",
    "Usta Büyücü Kaskı",
  ],
  "Eldiven": [
    "Pamuk Gezgin Eldiveni",
    "Kır Gezgini Eldiveni",
    "Doğa Gezgini Eldiveni",
    "İnce İpek Kumaş Eldiveni",
    "Karanlık Ölüm Gözetleme Eldiveni",
    "Yörük Koruyucu Eldiveni",
    "Gizli Gezgin Eldiveni",
    "Kraliyet Rehber Eldiveni",
    "Fidelis Eldiveni",
    "Yükselen Soylu Ruh Eldiveni",
    "Usta Büyücü Eldiveni",
  ],
  "Ayakkabı": [
    "Pamuk Gezgin Botu",
    "Kır Gezgini Botu",
    "Doğa Gezgini Botu",
    "İnce İpek Kumaş Botu",
    "Karanlık Ölüm Gözetleme Botu",
    "Yörük Koruyucu Botu",
    "Gizli Gezgin Botu",
    "Kraliyet Rehber Botu",
    "Fidelis Botu",
    "Yükselen Soylu Ruh Botu",
    "Usta Büyücü Botu",
  ],
};

export const ACCESSORY_NAMES_BY_LEVEL: Record<string, string[]> = {
  "Kolye": [
    "Koruma Amuleti",
    "Büyülü Kolye",
    "Sükunet Tılsımı",
    "Yürek Taşı Taki",
    "Yıldız Işığının Kolyesi",
  ],
  "Bilezik": [
    "Yakut Bilezik",
    "Anostia'nın İyi Şans Bileziği",
    "Hoşgörü Bileziği",
    "Eski Deri Bilezik",
    "İnanç Bileziği",
  ],
  "Küpe": [
    "Zümrüt Küpe",
    "İnci Küpe",
    "Şans Küpesi",
    "Beyaz Kraliçe'nin Bereketi",
    "Korsanın Küpesi",
  ],
  "Yüzük": [
    "Kreas'ın Gözü",
    "Gümüş Yüzük",
    "Nakışlı Yüzük",
    "Kuvartz Yüzük",
    "Gece Yüzüğü",
  ],
  "Çanta": [
    "Efsane Hırsızın Çantası",
    "Eski Keşişin Torbası",
    "Yolcu Çantası",
    "İnce Deri Çanta",
    "Sözleşmeli Avcının Çantası",
  ],
};

export const WEAPON_NAMES_BY_LEVEL: Record<string, string[]> = {
  "Kılıç": [
    "Ruh Yakıcı Kılıç",
    "Çaylak Kılıcı",
    "Çırak Kılıcı",
    "Yeni Başlayan Kılıcı",
    "Ejderha Ustası Kılıcı",
    "Gladyatör'ün Onur Kılıcı",
    "Çılgınlık Kılıcı",
    "Gazi Kılıcı",
    "Usta Kılıcı",
    "Arena Usta Kılıcı",
    "Elit Kılıç",
  ],
  "Kalkan": [
    "Koruma Kalkanı",
    "Acemi Kalkanı",
    "Duellist Kalkanı",
    "Çaylak Kalkanı",
    "Başlangıç ​​Kalkanı",
    "Yeni Başlayan Kalkanı",
    "Gazi Kalkanı",
    "Elit Kalkan",
    "Fırtına Duvarı Savunucusu",
    "Svalinn Kalkanı",
    "Son Adamın Kalkanı",
  ],
  "Çift El Kılıç": [
    "Kahramanların Kızıl Kılıcı",
    "Sabah Kılıcı",
    "Savaş Lordunun Kılıcı",
    "Çaylak Ağır Kılıcı",
    "Kolossus Kılıcı",
    "Onur Büyük Kılıcı",
    "Çaylak Ağır Kılıcı",
    "Elit Ağır Kılıç",
    "Gazi Ağır Kılıç",
    "Temel Ağır Kılıç",
    "Arena Usta Ağır Kılıç",
  ],
  "Mızrak": [
    "Çaylak Mızrak",
    "Zehirli Mızrak",
    "Keskin Kenar Mızrak",
    "Elit Mızrak",
    "Gazi Mızrak",
    "Duellist Mızrak",
    "Çaylak Mızrak",
    "Yeni Başlayan Mızrak",
    "Çırak Mızrak",
    "Lejyonun Mızrağı",
    "Tapınak Muhafızının Mızrağı",
  ],
  "Çift Balta": [
    "Çaylak Balta",
    "Yeni Başlayan Balta",
    "Kapı Bekçisi Balta",
    "Çırak Balta",
    "Gazi Balta",
    "Elit Balta",
    "Arena Usta Balta",
    "Titan Ölüm İkilisi",
    "Efsane İkilisi İnfaz Balta",
    "Usta Balta",
    "Hükümdarlık Bıçakları İki El",
  ],
  "Çift Bıçak": [
    "Gizli Hançer",
    "Çaylak Çift Hançer",
    "Elit Çift Hançer",
    "Yeni Başlayan Çift Hançer",
    "Yükselme Hançerleri",
    "Çelik Gölge Hançerleri",
    "Çaylak Çift Hançer",
    "Başlangıç ​​Çift Hançer",
    "Arena Usta Çift Hançer",
    "Usta Çift Hançer",
    "Gazi Çift Hançer",
  ],
  "Yay": [
    "Keskin Nişancının Yayı",
    "Huş Ağacı Okçusu",
    "Büyükusta'nın Ölüm Fısıldaması",
    "Elit Yay",
    "Arena Usta Yayı",
    "Usta Yay",
    "Yeni Başlayan Yay",
    "Başlangıç ​​Oku",
    "Yeni Katılımcının Arayıcısı",
    "Gölge Darbesi Yayı",
    "Çaylak Yay",
  ],
  "Arbalet": [
    "Avcının Yineleyici Kesen",
    "Çaylak Kesen",
    "Gazi Kesen",
    "Keskin Nişancının Kesen",
    "Çaylak Kesen",
    "Nişancının Keskin Kesen",
    "Aceminin Hızlı Atışı",
    "Elit Kesen",
    "Usta Kesen",
    "Arena Usta Kesen",
    "Başlangıç ​​Kesen",
  ],
  "Asa": [
    "Elit Asa",
    "Büyücünün Güç Asası",
    "Element Odak",
    "Başlangıç ​​Asası",
    "Büyücü'nün Manipülatörü",
    "Runelı Asa",
    "Gazi Asa",
    "Usta Asa",
    "Yeni Başlayan Asa",
    "Arena Usta Asa",
    "Çaylak Asa",
  ],
  "Yaşam Asa": [
    "Çaylak Hayat Asası",
    "Elit Hayat Asası",
    "Canın Zarafeti",
    "İksir Kucaklaması",
    "İyileştirme Limanı",
    "Hayat Getiren",
    "Yeni Başlayan Hayat Asası",
    "Gazi Hayat Asası",
    "Başlangıç ​​Hayat Asası",
    "Çaylak Hayat Asası",
    "Arena Usta Hayat Asası",
  ],
  "Savaş Çekici": [
    "Şansın Savaş Çekici",
    "Çaylak Savaş Çekici",
    "Demir Kırıcı",
    "Fırtına Taşıyıcı",
    "Yetenekçi'nin Savaş Çekici",
    "Elit Savaş Çekici",
    "Çaylak Savaş Çekici",
    "Gazi Savaş Çekici",
    "Usta'nın Savaş Çekici",
    "Arena Usta Savaş Çekici",
    "Başlangıç ​​Savaş Çekici",
  ],
};

export const SET_BONUSES = {
  legendary: [
    "Sovereign's Legacy (324-360)",
    "Ravager's Dominion (324-360)",
    "Divine Aegis (324-360)",
    "Tempestbound (324-360)",
    "Bladeweaver (324-360)",
    "Spellfire (324-360)",
    "Astral Conflux (324-360)",
    "Seraphic Grace Set (324-360)",
    "Fortress of Valor (324-360)",
    "Dragonclaw (324-360)",
    "Eldritch Catalyst (324-360)",
    "Divine Harmony (324-360)",
  ],
  epic: [
    "Warlord's Honor Set (270-323)",
    "Ironclad Fury Set (270-323)",
    "Guardian of Light Set (270-323)",
    "Whispering Gale Set (270-323)",
    "Bladewind Set (270-323)",
    "Etherstorm Set (270-323)",
    "Celestial Flame Set (270-323)",
    "Lifebinder Set (270-323)",
    "Stoneguard Set (270-323)",
    "Savage Strike Set (270-323)",
    "Mystic Conduit Set (270-323)",
    "Serene Blessing Set (270-323)",
  ],
  common: [
    "Guardian's Resolve Set (162-269)",
    "Steelbreaker Set (162-269)",
    "Sanctified Bastion Set (162-269)",
    "Sentinel's Guard Set (162-269)",
    "Shadowstrike Set (162-269)",
    "Arcane Wisp Set (162-269)",
    "Mystic Ember Set (162-269)",
    "Dawnbringer Set (162-269)",
    "Ironwall Defender Set (162-269)",
    "Swiftstrike Set (162-269)",
    "Arcane Focus Set (162-269)",
    "Lifeward Set (162-269)",
  ],
};

export const BASE_GRADE_PER_LEVEL: Record<number, number> = {
  1: 5,
  5: 10,
  10: 20,
  15: 30,
  20: 40,
  25: 50,
  30: 60,
  35: 70,
  40: 80,
  45: 90,
  50: 100,
  60: 120,
  75: 140,
  100: 160,
  110: 180,
};

export type DisplayRarity = 'legendary' | 'epic' | 'uncommon' | 'common' | 'standard';

export const RARITY_INFO: Record<DisplayRarity, { textColor: string; badgeColor: string; borderColor: string; headerColor: string; glowHex: string; iconBackgroundGradient: string; }> = {
    legendary: { textColor: 'text-orange-400', badgeColor: 'bg-orange-500', borderColor: 'border-[#4a2a0d]', headerColor: 'bg-gradient-to-b from-[#4a2a0d] to-[#2b1807]', glowHex: '#f97316', iconBackgroundGradient: 'linear-gradient(to bottom, #6a3a1a, #d47a3a)' },
    epic: { textColor: 'text-purple-400', badgeColor: 'bg-purple-600', borderColor: 'border-purple-800', headerColor: 'bg-gradient-to-b from-purple-900/50 to-purple-950/50', glowHex: '#a855f7', iconBackgroundGradient: 'linear-gradient(to bottom, #4c1d95, #8b5cf6)' },
    uncommon: { textColor: 'text-blue-400', badgeColor: 'bg-blue-600', borderColor: 'border-blue-800', headerColor: 'bg-gradient-to-b from-blue-900/50 to-blue-950/50', glowHex: '#3b82f6', iconBackgroundGradient: 'linear-gradient(to bottom, #1e40af, #3b82f6)' },
    common: { textColor: 'text-green-400', badgeColor: 'bg-green-600', borderColor: 'border-green-800', headerColor: 'bg-gradient-to-b from-green-900/50 to-green-950/50', glowHex: '#22c55e', iconBackgroundGradient: 'linear-gradient(to bottom, #166534, #22c55e)' },
    standard: { textColor: 'text-gray-300', badgeColor: 'bg-gray-600', borderColor: 'border-gray-700', headerColor: 'bg-gradient-to-b from-gray-800/80 to-gray-900/80', glowHex: '#9ca3af', iconBackgroundGradient: 'linear-gradient(to bottom, #374151, #6b7280)' },
};


// Rarity for set bonus logic
export type SetRarity = 'legendary' | 'epic' | 'common' | 'default';

export const SET_BONUS_DETAILS: Record<string, Record<number, string[]>> = {
  // Common
  "Guardian's Resolve Set": { 4: ["set_bonus_phy_dp", "set_bonus_hp"] },
  "Sentinel's Guard Set": { 4: ["set_bonus_phy_dp", "set_bonus_hp"] },
  "Steelbreaker Set": { 4: ["set_bonus_phy_ap", "set_bonus_hp"] },
  "Sanctified Bastion Set": { 4: ["set_bonus_hp", "set_bonus_healing_multiplier"] },
  "Shadowstrike Set": { 4: ["set_bonus_phy_ap", "set_bonus_hp"] },
  "Mystic Ember Set": { 4: ["set_bonus_magic_ap", "set_bonus_mp"] },
  "Dawnbringer Set": { 4: ["set_bonus_mp", "set_bonus_healing_multiplier"] },
  "Arcane Wisp Set": { 4: ["set_bonus_magic_ap", "set_bonus_hp"] },
  "Ironwall Defender Set": { 4: ["set_bonus_mp_regen", "set_bonus_evasion"] },
  "Swiftstrike Set": { 4: ["set_bonus_accuracy", "set_bonus_crit_chance"] },
  "Arcane Focus Set": { 4: ["set_bonus_mp_regen", "set_bonus_crit_chance"] },
  "Lifeward Set": { 4: ["set_bonus_hp_regen", "set_bonus_mp_regen"] },
  // Epic
  "Warlord's Honor Set": { 3: ["set_bonus_phy_dp", "set_bonus_magic_dp"], 4: ["set_bonus_hp"] },
  "Ironclad Fury Set": { 3: ["set_bonus_phy_ap", "set_bonus_phy_dp"], 4: ["set_bonus_hp"] },
  "Guardian of Light Set": { 3: ["set_bonus_phy_dp", "set_bonus_hp"], 4: ["set_bonus_healing_multiplier"] },
  "Whispering Gale Set": { 3: ["set_bonus_phy_ap", "set_bonus_phy_dp"], 4: ["set_bonus_hp"] },
  "Bladewind Set": { 3: ["set_bonus_phy_ap", "set_bonus_phy_dp"], 4: ["set_bonus_hp"] },
  "Etherstorm Set": { 3: ["set_bonus_magic_ap", "set_bonus_phy_dp"], 4: ["set_bonus_hp"] },
  "Celestial Flame Set": { 3: ["set_bonus_magic_ap", "set_bonus_hp"], 4: ["set_bonus_mp"] },
  "Lifebinder Set": { 3: ["set_bonus_hp", "set_bonus_mp"], 4: ["set_bonus_healing_multiplier"] },
  "Stoneguard Set": { 3: ["set_bonus_mp_regen", "set_bonus_evasion"], 4: ["set_bonus_speed"] },
  "Savage Strike Set": { 3: ["set_bonus_accuracy", "set_bonus_crit_chance"], 4: ["set_bonus_crit_multiplier"] },
  "Mystic Conduit Set": { 3: ["set_bonus_hp_regen", "set_bonus_mp_regen"], 4: ["set_bonus_crit_chance"] },
  "Serene Blessing Set": { 3: ["set_bonus_hp_regen", "set_bonus_mp_regen"], 4: ["set_bonus_healing_multiplier"] },
  // Legendary
  "Sovereign's Legacy": { 2: ["set_bonus_phy_ap", "set_bonus_phy_dp"], 3: ["set_bonus_magic_dp"], 4: ["set_bonus_hp"] },
  "Ravager's Dominion": { 2: ["set_bonus_phy_ap", "set_bonus_phy_dp"], 3: ["set_bonus_magic_dp"], 4: ["set_bonus_hp"] },
  "Divine Aegis": { 2: ["set_bonus_phy_dp", "set_bonus_magic_dp"], 3: ["set_bonus_hp"], 4: ["set_bonus_healing_multiplier"] },
  "Tempestbound": { 2: ["set_bonus_phy_ap", "set_bonus_phy_dp"], 3: ["set_bonus_magic_dp"], 4: ["set_bonus_hp"] },
  "Bladeweaver": { 2: ["set_bonus_phy_ap", "set_bonus_phy_dp"], 3: ["set_bonus_magic_dp"], 4: ["set_bonus_hp"] },
  "Spellfire": { 2: ["set_bonus_magic_ap", "set_bonus_phy_dp"], 3: ["set_bonus_magic_dp"], 4: ["set_bonus_hp"] },
  "Astral Conflux": { 2: ["set_bonus_magic_ap", "set_bonus_phy_dp"], 3: ["set_bonus_hp"], 4: ["set_bonus_mp"] },
  "Seraphic Grace Set": { 2: ["set_bonus_phy_dp", "set_bonus_hp"], 3: ["set_bonus_mp"], 4: ["set_bonus_healing_multiplier"] },
  "Fortress of Valor": { 2: ["set_bonus_hp_regen", "set_bonus_mp_regen"], 3: ["set_bonus_evasion"], 4: ["set_bonus_speed"] },
  "Dragonclaw": { 2: ["set_bonus_hp_regen", "set_bonus_accuracy"], 3: ["set_bonus_crit_chance"], 4: ["set_bonus_crit_multiplier"] },
  "Eldritch Catalyst": { 2: ["set_bonus_hp_regen", "set_bonus_mp_regen"], 3: ["set_bonus_crit_chance"], 4: ["set_bonus_crit_multiplier"] },
  "Divine Harmony": { 2: ["set_bonus_hp_regen", "set_bonus_mp_regen"], 3: ["set_bonus_evasion"], 4: ["set_bonus_healing_multiplier"] },
};


// --- PET CONSTANTS ---

export const PET_LEVELS: number[] = Array.from({ length: 40 }, (_, i) => i + 1);

export const PET_TYPES = [
  { nameKey: 'pet_type_01', code: '01', imageUrl: 'https://storage.cloud.google.com/qfitempictures/pet/1.png' },
  { nameKey: 'pet_type_02', code: '02', imageUrl: 'https://storage.cloud.google.com/qfitempictures/pet/2.png' },
  { nameKey: 'pet_type_03', code: '03', imageUrl: 'https://storage.cloud.google.com/qfitempictures/pet/3.png' },
  { nameKey: 'pet_type_04', code: '04', imageUrl: 'https://storage.cloud.google.com/qfitempictures/pet/4.png' },
  { nameKey: 'pet_type_05', code: '05', imageUrl: 'https://storage.cloud.google.com/qfitempictures/pet/5.png' },
  { nameKey: 'pet_type_06', code: '06', imageUrl: 'https://storage.cloud.google.com/qfitempictures/pet/6.png' },
  { nameKey: 'pet_type_07', code: '07', imageUrl: 'https://storage.cloud.google.com/qfitempictures/pet/7.png' },
  { nameKey: 'pet_type_08', code: '08', imageUrl: 'https://storage.cloud.google.com/qfitempictures/pet/8.png' },
  { nameKey: 'pet_type_09', code: '09', imageUrl: 'https://storage.cloud.google.com/qfitempictures/pet/9.png' },
  { nameKey: 'pet_type_10', code: '10', imageUrl: 'https://storage.cloud.google.com/qfitempictures/pet/10.png' },
  { nameKey: 'pet_type_11', code: '11', imageUrl: 'https://storage.cloud.google.com/qfitempictures/pet/11.png' },
  { nameKey: 'pet_type_12', code: '12', imageUrl: 'https://storage.cloud.google.com/qfitempictures/pet/12.png' },
  { nameKey: 'pet_type_13', code: '13', imageUrl: 'https://storage.cloud.google.com/qfitempictures/pet/13.png' },
  { nameKey: 'pet_type_14', code: '14', imageUrl: 'https://storage.cloud.google.com/qfitempictures/pet/14.png' },
  { nameKey: 'pet_type_15', code: '15', imageUrl: 'https://storage.cloud.google.com/qfitempictures/pet/15.png' },
  { nameKey: 'pet_type_16', code: '16', imageUrl: 'https://storage.cloud.google.com/qfitempictures/pet/16.png' },
  { nameKey: 'pet_type_17', code: '17', imageUrl: 'https://storage.cloud.google.com/qfitempictures/pet/17.png' },
  { nameKey: 'pet_type_18', code: '18', imageUrl: 'https://storage.cloud.google.com/qfitempictures/pet/18.png' },
  { nameKey: 'pet_type_19', code: '19', imageUrl: 'https://storage.cloud.google.com/qfitempictures/pet/19.png' },
  { nameKey: 'pet_type_20', code: '20', imageUrl: 'https://storage.cloud.google.com/qfitempictures/pet/20.png' },
  { nameKey: 'pet_type_21', code: '21', imageUrl: 'https://storage.cloud.google.com/qfitempictures/pet/21.png' },
  { nameKey: 'pet_type_22', code: '22', imageUrl: 'https://storage.cloud.google.com/qfitempictures/pet/22.png' },
  { nameKey: 'pet_type_23', code: '23', imageUrl: 'https://storage.cloud.google.com/qfitempictures/pet/23.png' },
  { nameKey: 'pet_type_24', code: '24', imageUrl: 'https://storage.cloud.google.com/qfitempictures/pet/24.png' },
];

export const PET_PROFESSIONS = [
  { nameKey: 'pet_profession_01', code: '01' },
  { nameKey: 'pet_profession_02', code: '02' },
  { nameKey: 'pet_profession_03', code: '03' },
  { nameKey: 'pet_profession_04', code: '04' },
  { nameKey: 'pet_profession_05', code: '05' },
  { nameKey: 'pet_profession_06', code: '06' },
  { nameKey: 'pet_profession_07', code: '07' },
  { nameKey: 'pet_profession_20', code: '20' },
];

export const PET_PROFESSION_DESCRIPTIONS: Record<string, string[]> = {
  '01': [ // Odunculuk
    'Odunculukta toplama hızı %10 artar. %1 ihtimalle 2x toplama şansı verir.',
    'Odunculukta toplama hızı %20 artar. %2 ihtimalle 2x toplama şansı verir.',
    'Odunculukta toplama hızı %30 artar. %3 ihtimalle 2x toplama şansı verir.',
    'Odunculukta toplama hızı %40 artar. %4 ihtimalle 2x toplama şansı verir.',
    'Odunculukta toplama hızı %50 artar. %5 ihtimalle 2x toplama şansı verir.',
  ],
  '02': [ // Madencilik
    'Madencilikte toplama hızı %10 artar. %1 ihtimalle 2x toplama şansı verir.',
    'Madencilikte toplama hızı %20 artar. %2 ihtimalle 2x toplama şansı verir.',
    'Madencilikte toplama hızı %30 artar. %3 ihtimalle 2x toplama şansı verir.',
    'Madencilikte toplama hızı %40 artar. %4 ihtimalle 2x toplama şansı verir.',
    'Madencilikte toplama hızı %50 artar. %5 ihtimalle 2x toplama şansı verir.',
  ],
  '03': [ // Hasat
    'Hasat toplama hızı %10 artar. %1 ihtimalle 2x toplama şansı verir.',
    'Hasat toplama hızı %20 artar. %2 ihtimalle 2x toplama şansı verir.',
    'Hasat toplama hızı %30 artar. %3 ihtimalle 2x toplama şansı verir.',
    'Hasat toplama hızı %40 artar. %4 ihtimalle 2x toplama şansı verir.',
    'Hasat toplama hızı %50 artar. %5 ihtimalle 2x toplama şansı verir.',
  ],
  '04': [ // Balıkçılık
    'Otomatik balık tutma süresi 1 saniye düşer. %1 ihtimalle 2x balık tutma şansı verir.',
    'Otomatik balık tutma süresi 2 saniye düşer. %2 ihtimalle 2x balık tutma şansı verir.',
    'Otomatik balık tutma süresi 3 saniye düşer. %3 ihtimalle 2x balık tutma şansı verir.',
    'Otomatik balık tutma süresi 4 saniye düşer. %4 ihtimalle 2x balık tutma şansı verir.',
    'Otomatik balık tutma süresi 5 saniye düşer. %5 ihtimalle 2x balık tutma şansı verir.',
  ],
  '05': [ // Avcılık
    'Avcılıkta 2 saklanma bonusu verir. %1 ihtimalle 2x toplama şansı verir.',
    'Avcılıkta 3 saklanma bonusu verir. %2 ihtimalle 2x toplama şansı verir.',
    'Avcılıkta 4 saklanma bonusu verir. %3 ihtimalle 2x toplama şansı verir.',
    'Avcılıkta 5 saklanma bonusu verir. %4 ihtimalle 2x toplama şansı verir.',
    'Avcılıkta 6 saklanma bonusu verir. %5 ihtimalle 2x toplama şansı verir.',
  ],
  '06': [ // Aşçılık
    'Aşçılıkta üretim hızı %10 artar. %1 ihtimalle 2x üretim şansı verir.',
    'Aşçılıkta üretim hızı %20 artar. %2 ihtimalle 2x üretim şansı verir.',
    'Aşçılıkta üretim hızı %30 artar. %3 ihtimalle 2x üretim şansı verir.',
    'Aşçılıkta üretim hızı %40 artar. %4 ihtimalle 2x üretim şansı verir.',
    'Aşçılıkta üretim hızı %50 artar. %5 ihtimalle 2x üretim şansı verir.',
  ],
  '07': [ // Kimyacılık
    'Kimyacılıkta üretim hızı %10 artar. %1 ihtimalle 2x üretim şansı verir.',
    'Kimyacılıkta üretim hızı %20 artar. %2 ihtimalle 2x üretim şansı verir.',
    'Kimyacılıkta üretim hızı %30 artar. %3 ihtimalle 2x üretim şansı verir.',
    'Kimyacılıkta üretim hızı %40 artar. %4 ihtimalle 2x üretim şansı verir.',
    'Kimyacılıkta üretim hızı %50 artar. %5 ihtimalle 2x üretim şansı verir.',
  ],
  '20': [ // Toplayıcı
    'Otomatik olarak her 2 saniyede 1 eşya toplar.',
    'Otomatik olarak her 1 saniyede 1 eşya toplar.',
    'Otomatik olarak her 1 saniyede 2 eşya toplar.',
    'Otomatik olarak her 1 saniyede 4 eşya toplar.',
    'Otomatik olarak her eşyayı toplar.',
  ],
};
