export const ITEM_IMAGES: Record<string, string> = {
    'Alaca Botu': 'https://storage.cloud.google.com/qfitempictures/zirh/alacabotu.png',
    'Alaca Eldiveni': 'https://storage.cloud.google.com/qfitempictures/zirh/alacaeldiveni.png',
    'Alaca Zırh': 'https://storage.cloud.google.com/qfitempictures/zirh/alacazirhi.png',
    "Anostia'nın İyi Şans Bileziği": 'https://storage.cloud.google.com/qfitempictures/aksesuar/anostianiniyisansbilezigi.png',
    'Beyaz Kraliçe\'nin Bereketi': 'https://storage.cloud.google.com/qfitempictures/aksesuar/beyazkraliceninbereketi.png',
    'Buz Bağlı Eldiven': 'https://storage.cloud.google.com/qfitempictures/zirh/buzbaglieldiven.png',
    'Buz Bağlı Zırh': 'https://storage.cloud.google.com/qfitempictures/zirh/buzbaglizirh.png',
    'Büyülü Kolye': 'https://storage.cloud.google.com/qfitempictures/aksesuar/buyulukolye.png',
    'Çaylak Muhafız Botu': 'https://storage.cloud.google.com/qfitempictures/zirh/caylakmuhafizbotu.png',
    'Çaylak Muhafız Eldiveni': 'https://storage.cloud.google.com/qfitempictures/zirh/caylakmuhafizeldiveni.png',
    'Çaylak Muhafız Zırhı': 'https://storage.cloud.google.com/qfitempictures/zirh/caylakmuhafizzirhi.png',
    'Çelik Bot': 'https://storage.cloud.google.com/qfitempictures/celikayakkabi.png',
    'Çelik Eldiven': 'https://storage.cloud.google.com/qfitempictures/celikeldiven.png',
    'Çelik Kask': 'https://storage.cloud.google.com/qfitempictures/celikkask.png',
    'Çelik Zırh': 'https://tokgozmakina.com.tr/JTPriv/celikzirh.png',
    'Çöl Avcısı Botu': 'https://storage.cloud.google.com/qfitempictures/colavcisiayak.png',
    'Çöl Avcısı Eldiveni': 'https://storage.cloud.google.com/qfitempictures/colavcisieldiven.png',
    'Çöl Avcısı Kaskı': 'https://storage.cloud.google.com/qfitempictures/colavcisikask.png',
    'Çöl Avcısı Zırhı': 'https://storage.cloud.google.com/qfitempictures/colavcisizirh.png',
    'Darp Edilmiş Muhafız Eldiveni': 'https://storage.cloud.google.com/qfitempictures/zirh/darpedilmismuhafizeldiveni.png',
    'Darp Edilmiş Muhafız Zırhı': 'https://storage.cloud.google.com/qfitempictures/zirh/darpedilmismuhafizzirhi.png',
    'Doğa Gezgini Botu': 'https://storage.cloud.google.com/qfitempictures/zirh/dogagezginibotu.png',
    'Doğa Gezgini Eldiveni': 'https://storage.cloud.google.com/qfitempictures/zirh/dogagezginieldiveni.png',
    'Doğa Gezgini Zırhı': 'https://storage.cloud.google.com/qfitempictures/zirh/dogagezginizirhi.png',
    'Dreadnought Eldiven': 'https://storage.cloud.google.com/qfitempictures/zirh/dreadnoughteldiven.png',
    'Dreadnought Zırhı': 'https://storage.cloud.google.com/qfitempictures/zirh/dreadnoughtzirhi.png',
    'Efsane Hırsızın Çantası': 'https://storage.cloud.google.com/qfitempictures/aksesuar/efsanehirsizincantasi.png',
    'Ejderha Derisi Eldiven': 'https://storage.cloud.google.com/qfitempictures/zirh/ejderhaderisieldiven.png',
    'Ejderha Derisi Zırhı': 'https://storage.cloud.google.com/qfitempictures/zirh/ejderhaderisizirhi.png',
    'Eski Deri Bilezik': 'https://storage.cloud.google.com/qfitempictures/aksesuar/eskideribilezik.png',
    'Eski Keşişin Torbası': 'https://storage.cloud.google.com/qfitempictures/aksesuar/eskikesisintorbasi.png',
    'Fidelis Botu': 'https://storage.cloud.google.com/qfitempictures/zirh/fidelisbotu.png',
    'Fidelis Eldiveni': 'https://storage.cloud.google.com/qfitempictures/zirh/fideliseldiveni.png',
    'Fidelis Zırhı': 'https://storage.cloud.google.com/qfitempictures/zirh/fideliszirhi.png',
    'Fırtınaya Dövülmüş Eldiven': 'https://storage.cloud.google.com/qfitempictures/zirh/firtinayadovulmuseldiven.png',
    'Fırtınaya Dövülmüş Zırh': 'https://storage.cloud.google.com/qfitempictures/zirh/firtinayadovulmuszirh.png',
    'Gece Yüzüğü': 'https://storage.cloud.google.com/qfitempictures/aksesuar/geceyuzugu.png',
    'Gizli Gezgin Botu': 'https://storage.cloud.google.com/qfitempictures/zirh/gizligezginbotu.png',
    'Gizli Gezgin Eldiveni': 'https://storage.cloud.google.com/qfitempictures/zirh/gizligezgineldiveni.png',
    'Gizli Gezgin Zırhı': 'https://storage.cloud.google.com/qfitempictures/zirh/gizligezginzirhi.png',
    'Gökler Eldiveni': 'https://storage.cloud.google.com/qfitempictures/zirh/goklereldiveni.png',
    'Gökler Zırhı': 'https://storage.cloud.google.com/qfitempictures/zirh/goklerzirhi.png',
    'Gölge Botu': 'https://storage.cloud.google.com/qfitempictures/zirh/golgebotu.png',
    'Gölge Eldiveni': 'https://storage.cloud.google.com/qfitempictures/zirh/golgeeldiveni.png',
    'Gölge Zırhı': 'https://storage.cloud.google.com/qfitempictures/zirh/golgezirhi.png',
    'Gümüş Bot': 'https://storage.cloud.google.com/qfitempictures/zirh/gumusbot.png',
    'Gümüş Eldiven': 'https://storage.cloud.google.com/qfitempictures/zirh/gumuseldiven.png',
    'Gümüş Yüzük': 'https://storage.cloud.google.com/qfitempictures/aksesuar/gumusyuzuk.png',
    'Gümüş Zırh': 'https://storage.cloud.google.com/qfitempictures/zirh/gumuszirh.png',
    'Gürültülü Eldiven': 'https://storage.cloud.google.com/qfitempictures/zirh/gurultulueldiven.png',
    'Gürültülü Zırh': 'https://storage.cloud.google.com/qfitempictures/zirh/gurultuluzirh.png',
    'Hafif Bot': 'https://storage.cloud.google.com/qfitempictures/zirh/hafifbot.png',
    'Hafif Eldiven': 'https://storage.cloud.google.com/qfitempictures/zirh/hafifeldiven.png',
    'Hafif Zırh': 'https://storage.cloud.google.com/qfitempictures/zirh/hafifzirh.png',
    'Hoşgörü Bileziği': 'https://storage.cloud.google.com/qfitempictures/aksesuar/hosgorubilezigi.png',
    'İnanç Bileziği': 'https://storage.cloud.google.com/qfitempictures/aksesuar/inancbilezigi.png',
    'İnce Deri Çanta': 'https://storage.cloud.google.com/qfitempictures/aksesuar/incedericanta.png',
    'İnce İpek Kumaş Botu': 'https://storage.cloud.google.com/qfitempictures/zirh/inceipekkumasbotu.png',
    'İnce İpek Kumaş Eldiveni': 'https://storage.cloud.google.com/qfitempictures/zirh/inceipekkumaseldiveni.png',
    'İnce İpek Kumaş Zırhı': 'https://storage.cloud.google.com/qfitempictures/zirh/inceipekkumaszirhi.png',
    'İnci Küpe': 'https://storage.cloud.google.com/qfitempictures/aksesuar/incikupe.png',
    'Kale Koruyucusu Botu': 'https://storage.cloud.google.com/qfitempictures/zirh/kalekoruyucusubotu.png',
    'Kale Koruyucusu Eldiveni': 'https://storage.cloud.google.com/qfitempictures/zirh/kalekoruyucusueldiveni.png',
    'Kale Koruyucusu Zırhı': 'https://storage.cloud.google.com/qfitempictures/zirh/kalekoruyucusuzirhi.png',
    'Kalkan Eldiveni': 'https://storage.cloud.google.com/qfitempictures/zirh/kalkaneldiveni.png',
    'Kalkan Zırhı': 'https://storage.cloud.google.com/qfitempictures/zirh/kalkanzirhi.png',
    'Kara Çelik Eldiven': 'https://storage.cloud.google.com/qfitempictures/zirh/karacelikeldiven.png',
    'Kara Çelik Zırh': 'https://storage.cloud.google.com/qfitempictures/zirh/karacelikzirh.png',
    'Karanlık Ölüm Gözetleme Botu': 'https://storage.cloud.google.com/qfitempictures/zirh/karanlikolumgozetlemezirhi.png',
    'Karanlık Ölüm Gözetleme Eldiveni': 'https://storage.cloud.google.com/qfitempictures/zirh/karanlikolumgozetlemeeldiveni.png',
    'Karanlık Ölüm Gözetleme Zırhı': 'https://storage.cloud.google.com/qfitempictures/zirh/karanlikolumgozetlemezirhi.png',
    'Kır Gezgini Botu': 'https://storage.cloud.google.com/qfitempictures/zirh/kirgezginibotu.png',
    'Kır Gezgini Eldiveni': 'https://storage.cloud.google.com/qfitempictures/zirh/kirgezginieldiveni.png',
    'Kır Gezgini Zırhı': 'https://storage.cloud.google.com/qfitempictures/zirh/kirgezginizirhi.png',
    'Korsanın Küpesi': 'https://storage.cloud.google.com/qfitempictures/aksesuar/korsaninkupesi.png',
    'Koruma Amuleti': 'https://storage.cloud.google.com/qfitempictures/aksesuar/korumaamuleti.png',
    'Kraliyet Rehber Botu': 'https://storage.cloud.google.com/qfitempictures/zirh/kraliyetrehberbotu.png',
    'Kraliyet Rehber Eldiveni': 'https://storage.cloud.google.com/qfitempictures/zirh/kraliyetrehbereldiveni.png',
    'Kraliyet Rehber Zırhı': 'https://storage.cloud.google.com/qfitempictures/zirh/kraliyetrehberzirhi.png',
    "Kreas'ın Gözü": 'https://storage.cloud.google.com/qfitempictures/aksesuar/kreasingozu.png',
    'Kuvartz Yüzük': 'https://storage.cloud.google.com/qfitempictures/aksesuar/kuvartzyuzuk.png',
    "Lord'un Vasal Botu": 'https://storage.cloud.google.com/qfitempictures/zirh/lordunvasalbotu.png',
    "Lord'un Vasal Eldiveni": 'https://storage.cloud.google.com/qfitempictures/zirh/lordunvasaleldiveni.png',
    "Lord'un Vasal Zırhı": 'https://storage.cloud.google.com/qfitempictures/zirh/lordunvasalzirhi.png',
    'Nakışlı Yüzük': 'https://storage.cloud.google.com/qfitempictures/aksesuar/nakisliyuzuk.png',
    'Orman Botu': 'https://storage.cloud.google.com/qfitempictures/zirh/ormanbotu.png',
    'Orman Eldiveni': 'https://storage.cloud.google.com/qfitempictures/zirh/ormaneldiveni.png',
    'Orman Zırhı': 'https://storage.cloud.google.com/qfitempictures/zirh/ormanzirhi.png',
    'Pamuk Gezgin Botu': 'https://storage.cloud.google.com/qfitempictures/zirh/pamukgezginbotu.png',
    'Pamuk Gezgin Eldiveni': 'https://storage.cloud.google.com/qfitempictures/zirh/pamukgezgineldiveni.png',
    'Pamuk Gezgin Zırhı': 'https://storage.cloud.google.com/qfitempictures/zirh/pamukgezginzirhi.png',
    'Sönük Kaşif Botu': 'https://storage.cloud.google.com/qfitempictures/zirh/sonukkasifbotu.png',
    'Sönük Kaşif Eldiveni': 'https://storage.cloud.google.com/qfitempictures/zirh/sonukkasifeldiveni.png',
    'Sönük Kaşif Zırhı': 'https://storage.cloud.google.com/qfitempictures/zirh/sonukkasifzirhi.png',
    'Sözleşmeli Avcının Çantası': 'https://storage.cloud.google.com/qfitempictures/zirh/sozlesmeliavcinincantasi.png',
    'Sükunet Tılsımı': 'https://storage.cloud.google.com/qfitempictures/aksesuar/sukunettilsimi.png',
    'Şahin Botu': 'https://storage.cloud.google.com/qfitempictures/zirh/sahinbotu.png',
    'Şahin Eldiveni': 'https://storage.cloud.google.com/qfitempictures/zirh/sahineldiveni.png',
    'Şahin Zırhı': 'https://storage.cloud.google.com/qfitempictures/zirh/sahinzirhi.png',
    'Şans Küpesi': 'https://storage.cloud.google.com/qfitempictures/aksesuar/sanskupesi.png',
    'Tapınakçı Eldiven': 'https://storage.cloud.google.com/qfitempictures/zirh/tapinakcieldiven.png',
    'Tapınakçı Zırhı': 'https://storage.cloud.google.com/qfitempictures/zirh/tapinakcizirhi.png',
    'Usta Büyücü Botu': 'https://storage.cloud.google.com/qfitempictures/ustaayak.png',
    'Usta Büyücü Eldiveni': 'https://storage.cloud.google.com/qfitempictures/ustaeldiven.png',
    'Usta Büyücü Kaskı': 'https://storage.cloud.google.com/qfitempictures/ustakask.png',
    'Usta Büyücü Zırhı': 'https://storage.cloud.google.com/qfitempictures/ustazirh.png',
    'Yakut Bilezik': 'https://storage.cloud.google.com/qfitempictures/aksesuar/yakutbilezik.png',
    'Yıldız Işığının Kolyesi': 'https://storage.cloud.google.com/qfitempictures/aksesuar/yildizisigikolye.png',
    'Yolcu Çantası': 'https://storage.cloud.google.com/qfitempictures/aksesuar/yolcucantasi.png',
    'Yörük Koruyucu Botu': 'https://storage.cloud.google.com/qfitempictures/zirh/yorukkoruyucubotu.png',
    'Yörük Koruyucu Eldiveni': 'https://storage.cloud.google.com/qfitempictures/zirh/yorukkoruyucueldiveni.png',
    'Yörük Koruyucu Zırhı': 'https://storage.cloud.google.com/qfitempictures/zirh/yorukkoruyucuzirhi.png',
    'Yükselen Soylu Ruh Botu': 'https://storage.cloud.google.com/qfitempictures/zirh/yukselensoyluruhbotu.png',
    'Yükselen Soylu Ruh Eldiveni': 'https://storage.cloud.google.com/qfitempictures/zirh/yukselensoyluruheldiveni.png',
    'Yükselen Soylu Ruh Zırhı': 'https://storage.cloud.google.com/qfitempictures/zirh/yukselensoyluruhzirhi.png',
    'Yürek Taşı Taki': 'https://storage.cloud.google.com/qfitempictures/aksesuar/yurektasitaki.png',
    'Zümrüt Küpe': 'https://storage.cloud.google.com/qfitempictures/aksesuar/zumrutkupe.png',
};
